/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.GUI;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class CapturaNombres extends javax.swing.JDialog {
    ArrayList<String> names = new ArrayList<>();
    /**
     * Creates new form CapturaNombres
     */
    public CapturaNombres(VentanaPrincipal parent) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(null);
        setTitle(parent.getAppName());
        addWindowListener(new java.awt.event.WindowAdapter(){
           public void WindowClosing(java.awt.event.WindowEvent e){
               System.exit(0);
           }
        });
    }
    
    ArrayList<String> getNames(){
        setVisible(true);
        return names;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbStart = new javax.swing.JButton();
        jtName1 = new javax.swing.JTextField();
        jtName2 = new javax.swing.JTextField();
        jtName3 = new javax.swing.JTextField();
        jtName4 = new javax.swing.JTextField();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        Titulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbStart.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbStart.setText("Empezar");
        jbStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbStartActionPerformed(evt);
            }
        });

        name1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name1.setText("Jugador 1:");

        name2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name2.setText("Jugador 2:");

        name3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name3.setText("Jugador 3:");

        name4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        name4.setText("Jugador 4:");

        Titulo.setEditable(false);
        Titulo.setBackground(new java.awt.Color(240, 240, 240));
        Titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Titulo.setText("Introduzca los participantes:");
        Titulo.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jbStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtName4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(name2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtName2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtName3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(name1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtName1))
                            .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(jtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name2)
                    .addComponent(jtName2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name3)
                    .addComponent(jtName3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name4)
                    .addComponent(jtName4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jbStart)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbStartActionPerformed
        // TODO add your handling code here:
        names.clear();
        if(jtName1.getText().length() != 0){
            names.add(jtName1.getText());
        }
        if(jtName2.getText().length() != 0){
            names.add(jtName2.getText());
        }
        if(jtName3.getText().length() != 0){
            names.add(jtName3.getText());
        }
        if(jtName4.getText().length() != 0){
            names.add(jtName4.getText());
        }
        
        if(names.size() < 2){
           JOptionPane.showMessageDialog(this, "ERROR. NO HAS INSERTADO MINIMO 2 JUGADORES.",VentanaPrincipal.getInstance().getAppName(), JOptionPane.ERROR_MESSAGE);
        }else{
            dispose();
        }
    }//GEN-LAST:event_jbStartActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Titulo;
    private javax.swing.JButton jbStart;
    private javax.swing.JTextField jtName1;
    private javax.swing.JTextField jtName2;
    private javax.swing.JTextField jtName3;
    private javax.swing.JTextField jtName4;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    // End of variables declaration//GEN-END:variables
}
