/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.GUI;

import View.DeepSpaceView;
import controller.Controller;
import deepspace.GameState;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame implements DeepSpaceView{

    static private VentanaPrincipal instance = null;
    private String appName;
    
    private VistaSpaceStationExamen stationView;
    private VistaEnemyStarShip  enemyView;
    
    static public VentanaPrincipal getInstance(){
        if(instance == null){
            instance = new VentanaPrincipal();
        }
        return instance;
    }
    /**
     * Creates new form VentanaPrincipal
     */
    private VentanaPrincipal() {
        initComponents();
        appName = "Deepspace 1.0";
        setTitle(appName);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter(){
            @Override
            public void windowClosing(java.awt.event.WindowEvent e){
                Controller.getInstance().finish(0);
            }
        });
    }
    
    public String getAppName(){
        return appName;
    }
    
    @Override
    public void updateView(){
        
        enemyPanel2.removeAll();
        enemyView = new VistaEnemyStarShip();
        enemyView.setEnemy(Controller.getInstance().getUIversion().getCurrentEnemy());
        enemyPanel2.add(enemyView);
        
        stationPanel.removeAll();
        stationView = new VistaSpaceStationExamen();
        stationView.setSpaceStationExamen(Controller.getInstance().getUIversion().getCurrentStation());
        stationPanel.add(stationView);
        
        enabledButtons();
        
        repaint();
        revalidate();
    }
    
    private void enabledButtons(){
        GameState gameState = Controller.getInstance().getState();
        if(gameState == GameState.INIT){
            combatButton.setEnabled(true);
            nextTurnButton.setEnabled(false);
            enemyView.setVisible(false);
        }
        if(gameState == GameState.BEFORECOMBAT){
            combatButton.setEnabled(true);
            nextTurnButton.setEnabled(false);
            enemyView.setVisible(false);
        }
        if(gameState == GameState.AFTERCOMBAT){
            combatButton.setEnabled(false);
            nextTurnButton.setEnabled(true);
            enemyView.setVisible(true);
        }
        if(gameState == GameState.CANNOTPLAY){
            combatButton.setEnabled(false);
            nextTurnButton.setEnabled(false);
            enemyView.setEnabled(false);
        }
    }
    
    @Override
    public void showView(){
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyPanel = new javax.swing.JPanel();
        combatButton = new javax.swing.JButton();
        nextTurnButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        stationPanel = new javax.swing.JPanel();
        enemyPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eep Space 1.0");

        enemyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout enemyPanelLayout = new javax.swing.GroupLayout(enemyPanel);
        enemyPanel.setLayout(enemyPanelLayout);
        enemyPanelLayout.setHorizontalGroup(
            enemyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        enemyPanelLayout.setVerticalGroup(
            enemyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        combatButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        combatButton.setText("COMBATIR");
        combatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combatButtonActionPerformed(evt);
            }
        });

        nextTurnButton.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        nextTurnButton.setText("Siguiente turno");
        nextTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextTurnButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Salir");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(stationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enemyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(enemyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(231, 231, 231))))
            .addGroup(layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(combatButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nextTurnButton)
                .addGap(18, 18, 18)
                .addComponent(exitButton)
                .addGap(0, 408, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(enemyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(enemyPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(stationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combatButton)
                    .addComponent(nextTurnButton)
                    .addComponent(exitButton))
                .addGap(327, 327, 327))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combatButtonActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().combat();
        updateView();
    }//GEN-LAST:event_combatButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().finish(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void nextTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextTurnButtonActionPerformed
        // TODO add your handling code here:
        Controller.getInstance().nextTurn();
        updateView();
    }//GEN-LAST:event_nextTurnButtonActionPerformed

    @Override
    public ArrayList<String> readNamePlayers(){
        CapturaNombres namesCapture = new CapturaNombres(this);
        
        return namesCapture.getNames();
    }
    
    @Override
    public boolean confirmExitMessage(){
        return (JOptionPane.showConfirmDialog(this, "¿Estás segur@ que deseas salir?",getAppName(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }
    
    @Override
    public void nextTurnNotAllowedMessage(){
        JOptionPane.showMessageDialog(this, "\n No puedes avanzar de turno, no has cumplido tu castigo", getAppName(), JOptionPane.ERROR_MESSAGE);
    }
    
    @Override
    public void lostCombatMessage(){
        JOptionPane.showMessageDialog(this, "Has PERDIDO el combate. \tCumple tu castigo.", getAppName(), JOptionPane.INFORMATION_MESSAGE);
    }
    
    @Override
    public void escapeMessage(){
        JOptionPane.showMessageDialog(this, "Has logrado escapar. \tEres una Gallina Espacial.", getAppName(), JOptionPane.INFORMATION_MESSAGE);
    }
    
    @Override
    public void wonCombatMessage(){
        JOptionPane.showMessageDialog(this, "Has GANADO el combate. \tDisfruta de tu botín.",getAppName(),JOptionPane.INFORMATION_MESSAGE);
    }
    
    @Override
    public void wonGameMessage(){
        JOptionPane.showMessageDialog(this, "\n \tHAS GANADO LA PARTIDA", getAppName(), JOptionPane.INFORMATION_MESSAGE);
    }
   
    @Override
    public void conversionMessage(){
        JOptionPane.showMessageDialog(this, "Has GANADO el combate. \nAdemás te has CONVERTIDO. \nDisfruta de tu botín", getAppName(), JOptionPane.INFORMATION_MESSAGE);
    }
    
    @Override
    public void noCombatMessage(){
        JOptionPane.showMessageDialog(this, "No puedes combatir en este momento", getAppName(), JOptionPane.ERROR_MESSAGE);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combatButton;
    private javax.swing.JPanel enemyPanel;
    private javax.swing.JPanel enemyPanel2;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton nextTurnButton;
    private javax.swing.JPanel stationPanel;
    // End of variables declaration//GEN-END:variables
}

