/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.GUI;

import controller.Controller;
import deepspace.HangarToUI;
import deepspace.ShieldToUI;
import deepspace.WeaponToUI;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author usuario
 */
public class VistaHangar extends javax.swing.JPanel {

    /**
     * Creates new form VistaHangar
     */
    public VistaHangar() {
        initComponents();
    }
    
    public void setHangar(HangarToUI h){
        if(h == null){
            setVisible(false);
        }else{
            hangarPanel.removeAll();
            String title = "Hangar con " + h.getMaxElements() + " lugares";
            hangarPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.BLACK), title));
            
            ArrayList<WeaponToUI> weapons = h.getWeapons();
            ArrayList<ShieldToUI> shieldBoosters = h.getShieldBoosters();
            
            for(int i = 0; i < weapons.size(); i++){
                VistaWeapon weaponView = new VistaWeapon();
                weaponView.setWeapon(weapons.get(i));
                hangarPanel.add(weaponView);
            }
            
            for(int i = 0; i < shieldBoosters.size(); i++){
                VistaShield shieldView = new VistaShield();
                shieldView.setShield(shieldBoosters.get(i));
                hangarPanel.add(shieldView);
            }
        }
        
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedWeapons(){
        ArrayList<Integer> selectedWeapons = new ArrayList<>();
        int i = 0;
        for(Component c : hangarPanel.getComponents()){
            if(c instanceof VistaWeapon){
                if(((VistaWeapon) c).isSelected()){
                    selectedWeapons.add(i);
                }
            }
            i++;
        }
        
        return selectedWeapons;
    }
    
    ArrayList<Integer> getselectedShields(){
        ArrayList<Integer> selectedShields = new ArrayList<>();
        int i = 0;
        for(Component c : hangarPanel.getComponents()){
            if(c instanceof VistaShield){
                if(((VistaShield) c).isSelected()){
                    selectedShields.add(i);
                }
            }
            i++;
        }
        
        return selectedShields;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hangarScroll = new javax.swing.JScrollPane();
        hangarPanel = new javax.swing.JPanel();

        hangarScroll.setBorder(null);
        hangarScroll.setViewportView(hangarPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(hangarScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(hangarScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel hangarPanel;
    private javax.swing.JScrollPane hangarScroll;
    // End of variables declaration//GEN-END:variables
}
