/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.GUI;

import deepspace.WeaponToUI;
/**
 *
 * @author usuario
 */
public class VistaWeapon extends javax.swing.JPanel{

    private boolean selected = false;
    /**
     * Creates new form VistaWeapon
     */
    public VistaWeapon() {
        initComponents();
        setOpaque(selected);
    }
    
    public boolean isSelected(){
        return selected;
    }
    
    void setWeapon(WeaponToUI weapon){
        power.setText(Float.toString(weapon.getPower()));
        type.setText(weapon.getType().toString());
        uses.setText(Integer.toString(weapon.getUses()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        power = new javax.swing.JLabel();
        titlePotencia = new javax.swing.JLabel();
        titleType = new javax.swing.JLabel();
        titleUsos = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        uses = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        power.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        power.setText("jLabel1");

        titlePotencia.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titlePotencia.setText("Potencia :");

        titleType.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleType.setText("Tipo :");

        titleUsos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleUsos.setText("Usos :");

        type.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        type.setText("jLabel1");

        uses.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        uses.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(titleUsos)
                        .addGap(18, 18, 18)
                        .addComponent(uses))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(titlePotencia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(power))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(titleType)
                        .addGap(26, 26, 26)
                        .addComponent(type)))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleType)
                    .addComponent(type))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlePotencia)
                    .addComponent(power))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleUsos)
                    .addComponent(uses))
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        selected = !selected;
        setOpaque(selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel power;
    private javax.swing.JLabel titlePotencia;
    private javax.swing.JLabel titleType;
    private javax.swing.JLabel titleUsos;
    private javax.swing.JLabel type;
    private javax.swing.JLabel uses;
    // End of variables declaration//GEN-END:variables
}
