/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.GUI;

import deepspace.LootToUI;

/**
 *
 * @author usuario
 */
public class VistaLoot extends javax.swing.JPanel {

    /**
     * Creates new form VistaLoot
     */
    public VistaLoot() {
        initComponents();
    }
    
    void setLoot(LootToUI loot){
        String eficiente1;
        if(loot.isGetEfficient())
            eficiente1 = "Sí";
        else
            eficiente1 = "No";
        eficiente.setText(eficiente1);
        hangar.setText(Integer.toString(loot.getnHangars()));
        medals.setText(Integer.toString(loot.getnMedals()));
        shields.setText(Integer.toString(loot.getnShields()));
        String spaceCity1;
        if(loot.isSpaceCity())
            spaceCity1 = "Sí";
        else
            spaceCity1 = "No";
        spaceCity.setText(spaceCity1);
        supplies.setText(Integer.toString(loot.getnSupplies()));
        weapons.setText(Integer.toString(loot.getnWeapons()));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hangar = new javax.swing.JLabel();
        medals = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        supplies = new javax.swing.JLabel();
        titleHangar = new javax.swing.JLabel();
        titleMedals = new javax.swing.JLabel();
        titleShields = new javax.swing.JLabel();
        titleSupplies = new javax.swing.JLabel();
        titleWeapons = new javax.swing.JLabel();
        weapons = new javax.swing.JLabel();
        titleEficiente = new javax.swing.JLabel();
        eficiente = new javax.swing.JLabel();
        titleSpaceCity = new javax.swing.JLabel();
        spaceCity = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Botín", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N

        hangar.setText("jLabel1");

        medals.setText("jLabel1");

        shields.setText("jLabel1");

        supplies.setText("jLabel1");

        titleHangar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleHangar.setText("Tamaño de hangar :");

        titleMedals.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleMedals.setText("Medallas :");

        titleShields.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleShields.setText("Escudos : ");

        titleSupplies.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleSupplies.setText("Combustible :");

        titleWeapons.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleWeapons.setText("Armas : ");

        weapons.setText("jLabel1");

        titleEficiente.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleEficiente.setText("Eficiente:");

        eficiente.setText("jLabel2");

        titleSpaceCity.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleSpaceCity.setText("Ciudad espacial:");

        spaceCity.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titleWeapons)
                                    .addGap(74, 74, 74))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(titleShields)
                                    .addGap(69, 69, 69)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(titleEficiente)
                                    .addGap(18, 18, 18)
                                    .addComponent(eficiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(titleHangar, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(weapons, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(titleSupplies)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(supplies))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shields)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(titleMedals)
                                        .addGap(32, 32, 32)
                                        .addComponent(medals)))
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hangar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleSpaceCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spaceCity, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleWeapons)
                    .addComponent(titleSupplies)
                    .addComponent(supplies, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weapons, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleShields)
                    .addComponent(titleMedals)
                    .addComponent(medals, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shields, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleHangar)
                    .addComponent(hangar, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eficiente, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(titleEficiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleSpaceCity)
                    .addComponent(spaceCity))
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eficiente;
    private javax.swing.JLabel hangar;
    private javax.swing.JLabel medals;
    private javax.swing.JLabel shields;
    private javax.swing.JLabel spaceCity;
    private javax.swing.JLabel supplies;
    private javax.swing.JLabel titleEficiente;
    private javax.swing.JLabel titleHangar;
    private javax.swing.JLabel titleMedals;
    private javax.swing.JLabel titleShields;
    private javax.swing.JLabel titleSpaceCity;
    private javax.swing.JLabel titleSupplies;
    private javax.swing.JLabel titleWeapons;
    private javax.swing.JLabel weapons;
    // End of variables declaration//GEN-END:variables
}
