/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.GUI;

import deepspace.SpaceStationToUI;

/**
 *
 * @author usuario
 */
public class VistaSpaceStationExamen extends javax.swing.JPanel {

    /**
     * Creates new form VistaSpaceStationExamen
     */
    public VistaSpaceStationExamen() {
        initComponents();
    }
    
    void setSpaceStationExamen(SpaceStationToUI estacion){
        stationName.setText(estacion.getName());
        numElements.setText(Integer.toString(estacion.getShieldBoosters().size() + estacion.getWeapons().size()));
        
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stationName = new javax.swing.JLabel();
        numElementsTitle = new javax.swing.JLabel();
        numElements = new javax.swing.JLabel();

        stationName.setText("jLabel1");

        numElementsTitle.setText("Número de elementos:");

        numElements.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stationName, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numElementsTitle)
                        .addGap(18, 18, 18)
                        .addComponent(numElements)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stationName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numElementsTitle)
                    .addComponent(numElements))
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel numElements;
    private javax.swing.JLabel numElementsTitle;
    private javax.swing.JLabel stationName;
    // End of variables declaration//GEN-END:variables
}
