/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View.GUI;

import deepspace.EnemyToUI;
import controller.Controller;
import deepspace.GameState;

/**
 *
 * @author usuario
 */
public class VistaEnemyStarShip extends javax.swing.JPanel {
    private VistaLoot lootView;
    private VistaDamage damageView;
    /**
     * Creates new form VistaEnemyStarShip
     */
    public VistaEnemyStarShip() {
        initComponents();
        
        repaint();
        revalidate();
    }
    
    void setEnemy(EnemyToUI e){
        enemyDamagePanel.removeAll();
        damageView = new VistaDamage();
        damageView.setDamage(e.getDamage(), "Pérdidas");
        enemyDamagePanel.add(damageView);
        
        enemyFire.setText(Float.toString(e.getAmmoPower()));
        
        enemyLootPanel.removeAll();
        lootView = new VistaLoot();
        lootView.setLoot(e.getLoot());
        enemyLootPanel.add(lootView);
        
        enemyName.setText(e.getName());
        enemyShield.setText(Float.toString(e.getShieldPower()));
        
        
        if(Controller.getInstance().getState() == GameState.BEFORECOMBAT || Controller.getInstance().getState() == GameState.INIT){
            setVisible(false);
        }else{
            setVisible(true);
        }
        
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enemyDamagePanel = new javax.swing.JPanel();
        enemyFire = new javax.swing.JLabel();
        enemyLootPanel = new javax.swing.JPanel();
        enemyName = new javax.swing.JLabel();
        enemyShield = new javax.swing.JLabel();
        enemyTitle = new javax.swing.JLabel();
        fireTitle = new javax.swing.JLabel();
        shieldTitle = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        enemyDamagePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        enemyFire.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enemyFire.setText("jLabel1");

        enemyLootPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        enemyName.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enemyName.setText("jLabel1");

        enemyShield.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enemyShield.setText("jLabel1");

        enemyTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        enemyTitle.setText("Enemigo : ");

        fireTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        fireTitle.setText("Potencia de fuego :");

        shieldTitle.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shieldTitle.setText("Potencia de defensa :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(enemyDamagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(enemyLootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(fireTitle)
                            .addGap(18, 18, 18)
                            .addComponent(enemyFire, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(shieldTitle)
                            .addGap(18, 18, 18)
                            .addComponent(enemyShield)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enemyTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enemyName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enemyTitle)
                    .addComponent(enemyName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fireTitle)
                    .addComponent(enemyFire, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enemyShield, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shieldTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enemyLootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(enemyDamagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel enemyDamagePanel;
    private javax.swing.JLabel enemyFire;
    private javax.swing.JPanel enemyLootPanel;
    private javax.swing.JLabel enemyName;
    private javax.swing.JLabel enemyShield;
    private javax.swing.JLabel enemyTitle;
    private javax.swing.JLabel fireTitle;
    private javax.swing.JLabel shieldTitle;
    // End of variables declaration//GEN-END:variables
}
