

package View.GUI;


import deepspace.DamageToUI;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;


public class VistaDamage extends JPanel{
    
    public VistaDamage() {
        initComponents();
    }
    
    void setDamage(DamageToUI damage, String title){
        if(damage == null){
            setVisible(false);
        }else{
            setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.BLACK),title));
            shields.setText(Integer.toString(damage.getNShields()));
            weapons.setText(damage.getWeaponInfo());
            repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleWeapons = new javax.swing.JLabel();
        titleShields = new javax.swing.JLabel();
        shields = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weapons = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Pérdidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(399, 124));

        titleWeapons.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleWeapons.setText("Armas :");

        titleShields.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        titleShields.setText("Escudos :");

        shields.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        shields.setText("jLabel2");

        weapons.setEditable(false);
        weapons.setBackground(new java.awt.Color(239, 239, 239));
        weapons.setColumns(20);
        weapons.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        weapons.setLineWrap(true);
        weapons.setRows(5);
        weapons.setBorder(null);
        jScrollPane1.setViewportView(weapons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titleWeapons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleShields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shields)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleShields)
                    .addComponent(shields))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(titleWeapons)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel shields;
    private javax.swing.JLabel titleShields;
    private javax.swing.JLabel titleWeapons;
    private javax.swing.JTextArea weapons;
    // End of variables declaration//GEN-END:variables
}
